# Generated by Django 3.2.14 on 2022-07-10 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.ManyToManyField(related_name='profile', to='room.Message'),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ManyToManyField(related_name='profile', to='room.Room'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
