# Generated by Django 3.2.14 on 2022-07-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20220710_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='avatar',
        ),
    ]
