# Generated by Django 3.2.14 on 2022-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_rename_picture_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
    ]
