# Generated by Django 3.2.14 on 2022-07-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_alter_message_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
