# Generated by Django 3.2.14 on 2022-07-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_remove_message_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.ManyToManyField(related_name='profile', to='room.Message'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ManyToManyField(related_name='profile', to='room.Room'),
        ),
    ]
