# Generated by Django 3.2.14 on 2022-07-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_auto_20220710_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
    ]
