# Generated by Django 3.2.14 on 2022-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0024_profile_message_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
