# Generated by Django 4.0.6 on 2022-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0026_auto_20220710_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
