# Generated by Django 4.0.6 on 2022-07-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0030_remove_room_online_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_delete_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
