# Generated by Django 4.0.6 on 2022-07-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0031_room_room_delete_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_delete_password',
            new_name='username',
        ),
    ]
