# Generated by Django 4.0.6 on 2022-07-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0032_rename_room_delete_password_room_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
