# Generated by Django 4.0.6 on 2022-07-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0034_alter_room_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
    ]
