# Generated by Django 4.0.6 on 2022-07-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0035_remove_room_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='username',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
